<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="7" hostname="NBCNITQAJ9K" name="qaautomation.august2021.APITest" tests="8" failures="0" timestamp="19 Sep 2021 05:00:09 GMT" time="0.068" errors="1">
  <testcase name="incorrectLoginAPI" time="0.000" classname="qaautomation.august2021.APITest">
    <skipped/>
  </testcase> <!-- incorrectLoginAPI -->
  <testcase name="configAPI" time="0.000" classname="qaautomation.august2021.APITest">
    <skipped/>
  </testcase> <!-- configAPI -->
  <testcase name="configAPI2" time="0.000" classname="qaautomation.august2021.APITest">
    <skipped/>
  </testcase> <!-- configAPI2 -->
  <testcase name="dashboardAPIWithSchema" time="0.000" classname="qaautomation.august2021.APITest">
    <skipped/>
  </testcase> <!-- dashboardAPIWithSchema -->
  <testcase name="fakeEmail" time="0.000" classname="qaautomation.august2021.APITest">
    <skipped/>
  </testcase> <!-- fakeEmail -->
  <testcase name="testLoginAPI" time="0.068" classname="qaautomation.august2021.APITest">
    <error type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
at qaautomation.august2021.BaseAPITest.testLoginAPI(BaseAPITest.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at qaautomation.august2021.utils.DataUtility.<clinit>(DataUtility.java:21)
... 21 more
]]>
    </error>
  </testcase> <!-- testLoginAPI -->
  <testcase name="userAPI" time="0.000" classname="qaautomation.august2021.APITest">
    <skipped/>
  </testcase> <!-- userAPI -->
  <testcase name="dashboardAPI" time="0.000" classname="qaautomation.august2021.APITest">
    <skipped/>
  </testcase> <!-- dashboardAPI -->
</testsuite> <!-- qaautomation.august2021.APITest -->
